In [1]:
import pandas as pd

data = pd.read_csv('data/finance数据集.csv')
data

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,1,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2
1,2,0,0.957151,43,1,0.640255,2678.0,4,0,0,0,1
2,3,0,0.640255,58,0,0.937641,4000.0,8,0,4,0,0
3,4,0,0.222222,35,0,0.250000,3500.0,6,0,2,0,1
4,5,1,0.888889,62,3,0.750000,2200.0,10,1,5,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...
70,71,0,0.444444,45,0,0.500000,3600.0,6,0,3,0,1
71,72,0,0.222222,32,0,0.250000,4900.0,4,0,1,0,1
72,73,1,0.666667,52,2,0.750000,2700.0,8,1,4,1,2
73,74,0,0.111111,29,0,0.125000,5600.0,3,0,1,0,0
74,75,0,0.888889,65,0,0.937500,2000.0,12,0,6,0,3

In [3]:
print(data.head())

   Unnamed: 0  SeriousDlqin2yrs  RevolvingUtilizationOfUnsecuredLines  age  \
0           1                 1                              0.766127   45
1           2                 0                              0.957151   43
2           3                 0                              0.640255   58
3           4                 0                              0.222222   35
4           5                 1                              0.888889   62

   NumberOfTime30-59DaysPastDueNotWorse  DebtRatio  MonthlyIncome  \
0                                     2   0.802982         9120.0
1                                     1   0.640255         2678.0
2                                     0   0.937641         4000.0
3                                     0   0.250000         3500.0
4                                     3   0.750000         2200.0

   NumberOfOpenCreditLinesAndLoans  NumberOfTimes90DaysLate  \
0                               13                        0
1                                4                        0
2                                8                        0
3                                6                        0
4                               10                        1

   NumberRealEstateLoansOrLines  NumberOfTime60-89DaysPastDueNotWorse  \
0                             6                                     0
1                             0                                     0
2                             4                                     0
3                             2                                     0
4                             5                                     1

   NumberOfDependents
0                   2
1                   1
2                   0
3                   1
4                   3

In [4]:
x = data.drop(['Unnamed: 0','SeriousDlqin2yrs'],axis=1)
y = data['SeriousDlqin2yrs']

In [5]:
x

,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,0.766127,45,2,0.802982,9120.0,13,0,6,0,2
1,0.957151,43,1,0.640255,2678.0,4,0,0,0,1
2,0.640255,58,0,0.937641,4000.0,8,0,4,0,0
3,0.222222,35,0,0.250000,3500.0,6,0,2,0,1
4,0.888889,62,3,0.750000,2200.0,10,1,5,1,3
...,...,...,...,...,...,...,...,...,...,...
70,0.444444,45,0,0.500000,3600.0,6,0,3,0,1
71,0.222222,32,0,0.250000,4900.0,4,0,1,0,1
72,0.666667,52,2,0.750000,2700.0,8,1,4,1,2
73,0.111111,29,0,0.125000,5600.0,3,0,1,0,0
74,0.888889,65,0,0.937500,2000.0,12,0,6,0,3

In [7]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(x_train,y_train)

LogisticRegression(max_iter=1000)

In [9]:
import pickle
with open('model.pkl','wb') as file:
    pickle.dump(model,file)

In [10]:
y_predict = model.predict(x_test)
b = pd.DataFrame(y_predict,columns=['预测结果'])

In [11]:
print(b)

    预测结果
0      1
1      0
2      1
3      0
4      0
5      0
6      0
7      0
8      0
9      1
10     1
11     1
12     0
13     1
14     0

In [12]:
a = (y_test == y_predict).mean()

In [13]:
print(a)

0.9333333333333333

In [15]:
from sklearn.metrics import classification_report
report = classification_report(y_test,y_predict,zero_division=1)
print(report)

              precision    recall  f1-score   support

           0       0.89      1.00      0.94         8
           1       1.00      0.86      0.92         7

    accuracy                           0.93        15
   macro avg       0.94      0.93      0.93        15
weighted avg       0.94      0.93      0.93        15

In [16]:
with open('report.txt','w') as file:
    file.write(report)

In [17]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)
x_resampled,y_resampled = smote.fit_resample(x_train,y_train)

In [18]:
len(x_resampled)

96

In [19]:
model.fit(x_resampled,y_resampled)

LogisticRegression(max_iter=1000)

In [20]:
y_repredict = model.predict(x_test)

In [22]:
a = (y_test==y_predict).mean()
print(a)

0.9333333333333333

In [23]:
pd.DataFrame(y_repredict, columns=["预测结果"]).to_csv("预测结果.txt",index=False)

In [24]:
re_report = classification_report(y_test,y_repredict,zero_division=1)
with open('re_report.txt','w') as file:
    file.write(re_report)