In [2]:
import pandas as pd

data = pd.read_csv('data/auto-mpg.csv')
data.tail()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
25,14.0,8,455.0,225.0,4425,10.0,70,1,pontiac catalina
26,19.0,6,232.0,100.0,2634,13.0,70,1,chevrolet vega
27,20.0,4,97.0,88.0,2130,17.0,70,3,volkswagen super beetle
28,16.0,6,225.0,105.0,3024,15.5,70,1,dodge dart custom
29,13.0,8,350.0,165.0,3693,14.5,70,1,buick skylark 320

In [3]:
print(data.dtypes)

mpg             float64
cylinders         int64
displacement    float64
horsepower      float64
weight            int64
acceleration    float64
model year        int64
origin            int64
car name         object
dtype: object

In [6]:
print(data.isnull().sum())
data = data.dropna()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [7]:
data['horsepower'] = pd.to_numeric(data['horsepower'])

In [8]:
print(data['horsepower'].dtypes)

float64

In [13]:
data.tail()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
25,14.0,8,1.474457,1.731672,1.742110,-0.937584,70,1,pontiac catalina
26,19.0,6,-0.646402,-0.962838,-1.140128,0.144244,70,1,chevrolet vega
27,20.0,4,-1.930330,-1.221512,-1.951211,1.586681,70,3,volkswagen super beetle
28,16.0,6,-0.712976,-0.855058,-0.512505,1.045767,70,1,dodge dart custom
29,13.0,8,0.475846,0.438307,0.564110,0.685158,70,1,buick skylark 320

In [11]:
data = data.dropna(subset=['horsepower'])

In [12]:
numerical_features = ['displacement', 'horsepower', 'weight', 'acceleration']
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
data[numerical_features] = scaler.fit_transform(data[numerical_features])
data.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,0.066891,-0.316156,0.259954,-0.216366,70,1,chevrolet chevelle malibu
1,15.0,8,0.475846,0.438307,0.564110,-0.396670,70,1,buick skylark 320
2,18.0,8,0.171507,0.114966,0.150522,-0.576975,70,1,plymouth satellite
3,16.0,8,0.038359,0.114966,0.145694,-0.216366,70,1,amc rebel sst
4,17.0,8,0.019338,-0.100595,0.171443,-0.757279,70,1,ford torino

In [15]:
selected_features = ['cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model year', 'origin']
x = data[selected_features]
y = data['mpg']

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [17]:
len(data)

30

In [18]:
len(x_test)

6

In [19]:
type(train_test_split(x,y,test_size=0.2,random_state=42))

list

In [20]:
x_test

,cylinders,displacement,horsepower,weight,acceleration,model year,origin
27,4,-1.930330,-1.221512,-1.951211,1.586681,70,3
15,6,-0.960251,-1.027507,-0.914828,1.045767,70,1
23,8,0.038359,0.114966,0.145694,-0.216366,70,1
17,4,-1.778161,-1.070619,-1.561762,0.865462,70,3
8,8,1.474457,1.731672,1.742110,-0.937584,70,1
9,8,0.856269,0.977209,0.816768,-1.478498,70,1

In [21]:
cleanedData = x.copy()
cleanedData['mpg'] = y
cleanedData.to_csv('cleanedData.csv',index=False)